---
- hosts: all
  remote_user: root
- name: Register as user (joe_user) with password (somepass) and auto-subscribe to available content.
  redhat_subscription:
    state: present
    username: jason@nikoyo.cn
    password: erYqRabsHZ
    auto_attach: true